# /**/yolo_ros:
/**:
  ros__parameters:
    keypoint_publish_names:
      - "nose"
      # - "left_eye"
      # - "right_eye"
      # - "left_ear"
      # - "right_ear"
      # - "left_shoulder"
      # - "right_shoulder"
      # - "left_elbow"
      # - "right_elbow"
      # - "left_wrist"
      # - "right_wrist"
      # - "left_hip"
      # - "right_hip"
      # - "left_knee"
      # - "right_knee"
      # - "left_ankle"
      # - "right_ankle"


    # 空にすると person キーポイント判定は無効
    # person_keypoint_filter_names: []
    person_keypoint_filter_names:
      - "nose"

    # 空にするとキーポイント導線は無効
    # keypoint_trail_names: []
    keypoint_trail_names:
      - "left_eye"
      - "right_eye"
